# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LocalHeritageAI
                                 A QGIS plugin
 local_heritage_ai
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-17
        copyright            : (C) 2026 by Mohamed W. Fareed
        email                : mw.fareed@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load LocalHeritageAI class from file LocalHeritageAI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LocalHeritageAI import LocalHeritageAI
    return LocalHeritageAI(iface)
